group: travis_latest
dist: xenial
language: python
python:
  - "3.7"
install:
  - cd server
  - pip install -r requirements.txt
  - pip install codecov pytest-cov
script:
  - pytest --cov=./
after_success:
  - codecov